<?php

namespace Vae\PhpElasticsearchOrm\Test;

use PHPUnit\Framework\TestCase;
use Vae\PhpElasticsearchOrm\Builder;
use Vae\PhpElasticsearchOrm\Factory;

class Test extends TestCase
{
    /** @var Builder */
    public static $builder;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        $config = require __DIR__ . '/../config/elasticsearch.php';
        $config['hosts'] = [
            ['host' => '127.0.0.1:9200']
        ];
        static::$builder = Factory::builder($config);
    }

    /**
     * @doesNotPerformAssertions
     * @return object
     * Created by hongshuobin 2022/6/6 17:15
     * @throws \Exception
     */
    public function testCreate()
    {
        $result = static::$builder->index('test')->create(['key' => 'value']);
        var_dump($result);
        return $result;
    }
}